 FROM arm32v6/python:3.9-alpine
 #FROM ARM32v6/python3.9-alpine AS prod 
 # docker build -t docker --target prod -> multistage docker zeugs

# gcc needed for python RPi.GPIO library
RUN apk update
RUN apk add python3-dev \
            gcc \
            libc-dev \
            libffi-dev

WORKDIR /SDP

ENV FLASK_APP=app
EXPOSE 5000
COPY requirements/base.txt requirements/base.txt

RUN pip3 install -r requirements/base.txt

COPY . .

CMD ["FLASK_APP=app"]
CMD ["python3","-m","flask","run","--host=0.0.0.0"]


#FROM arm32v6/python:3.9-alpine AS dev
