name: build docker test stage

on:
  push:
    branches: [ "feature"]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: docker/build-push-action@v3.2.0
    - run: docker build . --file Dockerfile --tag projekt:test
