name: docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    types:
      - closed
    branches:
      - 'master'
  
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker"
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sdp:test
          target: test
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker"
          platforms: linux/amd64,linux/arm64,linux/arm/v6
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sdp:production
          target: production
